<?php

/**
 * Implements hook_preprocess().
 */
function bc_citation_preprocess(&$variables, $hook)
{
  // if object && object->cite add $variables['cite'] (or nvm...)
}

/**
 * Implements hook_islandora_view_object().
 */
function bc_citation_islandora_view_object($object, $user, $page_number, $page_size = '')
{
  if ($mods = $object['MODS']->content) {
    $style = variable_get('bc_citation_csl_style', CSL::GetDefaultName());
    $style_array = citeproc_style($style);
    $cite = 'Citation for this item: ' . citeproc_bibliography_from_mods($style_array, $mods);
    $object->cite = $cite;
    $for_debug = array();
    $for_debug['MODS'] = $mods;
    $for_debug['CSL'] = $style_array;
    $for_debug['CITE'] = $cite;
    dpm($for_debug, 'Citation Debug Data', 'warning');
  }
}

/**
 * Implements hook_islandora_view_object_alter().
 */
function bc_citation_islandora_view_object_alter(&$object, &$rendered)
{
  $rendered['cite']['#markup'] = $object->cite ? $object->cite : NULL;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bc_citation_form_bc_islandora_config_alter(&$form, &$form_state, $form_id)
{
  $styles = CSL::GetNames();

  $form['bc_citation_csl_style'] = array(
    '#type' => 'select',
    '#title' => t('Select the CSL style to use when creating citations.'),
    '#options' => $styles,
    '#default_value' => CSL::GetDefaultName(),
  );

}

